# [PerWorldTablistPlugin] - A very simple plugin to separate your server
# tablist per world groups. If you have any issues, please contact me on
# Discord or create a new issue on this plugin's repository.

# Plugin Creator: Jairusu
# Discord Username: @jairusu
# Github: https://github.com/jairusudanieru

# The names of the worlds are case-sensitive.
# You can add more groups here, just follow the format below.
worldGroups:
  survival:
    worlds:
      - world
      - world_nether
      - world_the_end
  lobby:
    worlds:
      - hub
      - lobby
